build-docker:
  image: docker:stable
  services:
    - docker:dind
  only:
    - master
  stage: build-docker
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
deploy:
  stage: deploy
  image:
    name: dtzar/helm-kubectl:latest
  script:
    - kubectl create secret docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$CI_DEPLOY_USER" --docker-password="$CI_DEPLOY_PASSWORD" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run=client | kubectl apply -f -
    - helm upgrade --install ivaoth-discord-bot ./helm/ -f $VALUES_YAML --set image.tag=$CI_COMMIT_SHA,GitLab.app=$CI_PROJECT_PATH_SLUG,GitLab.env=$CI_ENVIRONMENT_SLUG
  environment:
    name: production
  only:
    - master

stages:
  - build-docker
  - deploy
