kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
data:
  IVAOTHAI_GUILD: {{ quote .Values.appConfig.IVAOTHAI_GUILD }}
  VERIFIED_ROLE: {{ quote .Values.appConfig.VERIFIED_ROLE }}
  ANNOUNCEMENT_CHANNEL: {{ quote .Values.appConfig.ANNOUNCEMENT_CHANNEL }}
  BOT_TOKEN: {{ quote .Values.appConfig.BOT_TOKEN }}
  API_KEY: {{ quote .Values.appConfig.API_KEY }}
  API_BASE_URI: {{ quote .Values.appConfig.API_BASE_URI }}
