kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
data:
  GOOGLE_CLOUD_PROJECT: {{ quote .Values.appConfig.GOOGLE_CLOUD_PROJECT }}
  GOOGLE_APPS_CREDENTIALS: {{ quote .Values.appConfig.GOOGLE_APPS_CREDENTIALS }}
  IVAOTHAI_GUILD: {{ quote .Values.appConfig.IVAOTHAI_GUILD }}
  VERIFIED_ROLE: {{ quote .Values.appConfig.VERIFIED_ROLE }}
  THAILAND_DIVISION_ROLE: {{ quote .Values.appConfig.THAILAND_DIVISION_ROLE }}
  OTHER_DIVISION_ROLE: {{ quote .Values.appConfig.OTHER_DIVISION_ROLE }}
  THAILAND_DIVISION_STAFF_ROLE: {{ quote .Values.appConfig.THAILAND_DIVISION_STAFF_ROLE }}
  OTHER_DIVISION_STAFF_ROLE: {{ quote .Values.appConfig.OTHER_DIVISION_STAFF_ROLE }}
  HQ_STAFF_ROLE: {{ quote .Values.appConfig.HQ_STAFF_ROLE }}
  UNVERIFIED_ROLE: {{ quote .Values.appConfig.UNVERIFIED_ROLE }}
  ANNOUNCEMENT_CHANNEL: {{ quote .Values.appConfig.ANNOUNCEMENT_CHANNEL }}
  BOT_TOKEN: {{ quote .Values.appConfig.BOT_TOKEN }}
  API_KEY: {{ quote .Values.appConfig.API_KEY }}
  MANAGED_ROLES: {{ quote .Values.appConfig.MANAGED_ROLES }}
